burnc_dir = "/home/elizabeth/repos/kaldi/egs/burnc/kaldi_features/data"
#out_dir = "/home/elizabeth/repos/kaldi/egs/burnc/kaldi_features/data/train_breath_tok"
#out_dir = "/home/elizabeth/repos/kaldi/egs/burnc/kaldi_features/data/train"
#out_dir = "/home/elizabeth/repos/kaldi/egs/burnc/kaldi_features/data/train_breath_sent"
out_dir = "/afs/inf.ed.ac.uk/group/project/prosody/stars/preproc/burnc_breath"