VERBOSE: False
LENGTH_ANALYSIS: False
print_every: 500
eval_every:
train_per: 0.6
dev_per: 0.2

tok_level_pred: True
batch_size: 64
include_lstm: True
bidirectional: True
learning_rate: 0.001
hidden_size: 512
pad_len: 2150
datasource: 'BURNC'
num_epochs: 25
LSTM_LAYERS: 2
dropout: 0.5
feat_dim: 6
context: False

seed: 153

text_data: '../data/burnc/text2labels_breath_tok'
speech_data: '../data/burnc/burnc_breath_opensmilefeats.pkl'
#labels_data: '../data/burnc/burnc_last_label_dict_breath.pkl'
labels_data: '../data/burnc/burnc_label_dict_breath_tok.pkl'
toktimes_data: '../data/burnc/burnc_toktimes_breath_tok.pkl'
model_name: 'cnn_lstm_open_seed153_gc_bi'
results_path: 'results/burnc/seq_tagging/cnn_lstm_crossval/open'


train_params:
  batch_size: 1
  shuffle: True
  num_workers: 6

eval_params:
  batch_size: 1
  shuffle: True
  num_workers: 6
