VERBOSE: False
LENGTH_ANALYSIS: False
print_every: 500
eval_every:
train_per: 0.6
dev_per: 0.2

batch_size: 64
bidirectional: False
learning_rate: 0.001
hidden_size: 512
pad_len: 700
datasource: 'BURNC'
num_epochs: 100
LSTM_LAYERS: 2
dropout: 0.5

text_data: '../data/burnc/text2labels_breath_tok'
speech_data: '../data/burnc/burnc_mfcc_dict_breath.pkl'
labels_data: '../data/burnc/burnc_last_label_dict_breath.pkl'
model_name: 'burnc_breath'
results_path: 'results'


train_params:
  batch_size: 32
  shuffle: True
  num_workers: 6

eval_params:
  batch_size: 32
  shuffle: True
  num_workers: 6