# dataloader params
segmentation: utterances
context_window: False
datasplit: ../data/burnc/splits/debug.yaml
feats: tok2pros
bitmark: False

# Debugging params
VERBOSE: False
LENGTH_ANALYSIS: False
print_every: 500
eval_every:


# i/o params
all_data: '../data/burnc/burnc.pkl'
model_name: 'cnn_lstm_debug'
results_path: 'results/refactor/'

train_params:
  batch_size: 5
  shuffle: True
  num_workers: 6

eval_params:
  batch_size: 5
  shuffle: True
  num_workers: 6

# Model params
tok_level_pred: True
include_lstm: True
bidirectional: True
learning_rate: 0.001
hidden_size: 512
frame_pad_len: 2150
tok_pad_len: 50
pad_len: 2150
num_epochs: 5
cnn_layers: 2
lstm_layers: 2
dropout: 0.5
feat_dim: 6
postlstm_context: False
context: False
weight_decay: 0
flatten_method: max
frame_filter_size: 9
frame_pad_size: 4


seed: 256
