# dataloader params
segmentation: utterances
context_window: False
datasplit: ../data/burnc/splits/tenfold0.yaml
#datasplit: ../data/burnc/splits/fivefold0.yaml
feats: tok2pros
bitmark: True

# Debugging params
VERBOSE: False
LENGTH_ANALYSIS: False
print_every: 500
eval_every:


# i/o params
all_data: '../data/burnc/burnc.pkl'
model_name: 'cnn_lstm_pros_gc_bi_wde6'
results_path: 'results/refactor/cnn_lstm'

train_params:
  batch_size: 64
  shuffle: True
  num_workers: 6

eval_params:
  batch_size: 64
  shuffle: True
  num_workers: 6

# Model params
tok_level_pred: True
batch_size: 1
include_lstm: True
bidirectional: True
learning_rate: 0.001
hidden_size: 128
pad_len: 2150
frame_pad_len: 2150
tok_pad_len: 50
num_epochs: 25
cnn_layers: 3
lstm_layers: 2
dropout: 0.5
feat_dim: 6
postlstm_context: False
weight_decay: 0.00001
flatten_method: sum
frame_filter_size: 11
frame_pad_size: 5


# Text-specific params
inputs: speech
embedding_dim: 300
use_pretrained: True
vocab_size: 3000
glove_path: '../data/emb/glove.6B.100d.txt'
bottleneck_feats: 2000





seed: 256
