# dataloader params
segmentation: utterances
context_window: False
datasplit: /disk/scratch/s1899827/stars/data/tenfold0.yaml
feats: tok2pros
bitmark: True

# Debugging params
VERBOSE: False
LENGTH_ANALYSIS: False
print_every: 500
eval_every:


# i/o params
all_data: '/disk/scratch/s1899827/stars/data/burnc.pkl'
model_name: 'cnn_lstm_pros_gc_bi'
results_path: '/disk/scratch/s1899827/results'

train_params:
  batch_size: 64
  shuffle: True
  num_workers: 6

eval_params:
  batch_size: 64
  shuffle: True
  num_workers: 6

# Model params
tok_level_pred: True
batch_size: 1
include_lstm: True
bidirectional: True
learning_rate: 0.001
hidden_size: 512
pad_len: 2150
frame_pad_len: 2150
tok_pad_len: 50
num_epochs: 25
cnn_layers: 2
lstm_layers: 2
dropout: 0
feat_dim: 6
postlstm_context: False
weight_decay: 0.001
flatten_method: sum
frame_filter_size: 9
frame_pad_size: 4


seed: 256
