# dataloader params
segmentation: tokens
context_window: True
datasplit: ../data/burnc/splits/debug.yaml
feats: tok2pros
bitmark: True

# Debugging params
VERBOSE: False
LENGTH_ANALYSIS: False
print_every: 500
eval_every:

# i/o params
all_data: '../data/burnc/burnc.pkl'
model_name: 'replication_debug'
results_path: 'results/refactor'

train_params:
  batch_size: 32
  shuffle: True
  num_workers: 6
eval_params:
  batch_size: 32
  shuffle: True
  num_workers: 6

# model params
tok_level_pred: False
include_lstm: False
bidirectional: False
learning_rate: 0.001
hidden_size: 512
frame_pad_len: 420
tok_pad_len: None
num_epochs: 5
cnn_layers: 2
lstm_layers: 2
dropout: 0.2
feat_dim: 7
#feat_dim: 6
postlstm_context: False
weight_decay: 0

seed: 131
