VERBOSE: False
LENGTH_ANALYSIS: False
print_every: 500
eval_every:
train_per: 0.6
dev_per: 0.2

batch_size: 64
include_lstm: False
bidirectional: False
learning_rate: 0.001
hidden_size: 512
pad_len: 700
datasource: 'SWBDNXT_UTT'
num_epochs: 50
LSTM_LAYERS: 2
dropout: 0.5

text_data: '../data/utterances.txt'
speech_data: '../data/cmvn_tensors.pkl'
labels_data: '../data/utterances_labels.pkl'
#model_name: 'full_model_hardtanh_last_d5_l2_b32_e50_batcheval'
model_name: 'cnn_only_hardtanh_last_d5_l2_b32_e50_batcheval'
results_path: 'results'


train_params:
  batch_size: 32
  shuffle: True
  num_workers: 6

eval_params:
  batch_size: 32
  shuffle: True
  num_workers: 6