speech_dir: /afs/inf.ed.ac.uk/group/project/prosody/prosody_nlp/data/input_features/turn_part_fixed
seed: 0
datasplit: 'train'

model_name: 'swbd_seg_w_interstices'

train_params:
  batch_size: 64
  shuffle: True
  num_workers: 6

eval_params:
  batch_size: 64
  shuffle: True
  num_workers: 6


frame_pad_len: 55164
tok_pad_len: 258
vocab_size: 14555

use_pretrained: True
embedding_dim: 300
inputs: both
embedding_dim: 300
glove_path_100: '../data/emb/glove.6B.100d.txt'
glove_path_300: '../data/emb/glove.6B.300d.txt'

tok_level_pred: True
batch_size: 1
include_lstm: True
bidirectional: True
learning_rate: 0.001
hidden_size: 128
pad_len: 2150
num_epochs: 25
cnn_layers: 3
lstm_layers: 2
dropout: 0.5
feat_dim: 6
postlstm_context: False
weight_decay: 0.00001
flatten_method: sum
frame_filter_size: 11
frame_pad_size: 5
num_classes: 2
bottleneck_feats: 2000

results_path: seg_output