batch_size: 64
bidirectional: true
datafile: ../data/burnc/text2labels_breath_tok
datasource: BURNC
dev_ratio: 0.2
dropout: 0.5
embedding_dim: 300
eval_every: 500
glove_path: ../data/emb/glove.6B.300d.txt
hidden_size: 128
learning_rate: 0.001
max_len: 80
model_name: full_eval_burnc_breath_smaller_l2_b64-d5-e20-v3100-lr001-glove
model_type: lstm
num_epochs: 20
num_layers: 2
print_dims: false
print_every: 50
results_path: results/burnc
seed: 0
train_ratio: 0.6
use_pretrained: false
vocab_size: 3100
